name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Executa o workflow quando há alterações na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Passo 3: Garantir a existência da branch gh-pages
      - name: Create gh-pages Branch if Necessary
        run: |
          git fetch origin || echo "Nenhuma branch encontrada ainda"
          git branch -D gh-pages || echo "A branch gh-pages não existe"
          git checkout --orphan gh-pages
          git reset --hard
          git clean -fdx
          echo "GitHub Pages inicializado" > index.html
          git add index.html
          git commit -m "Inicializar a branch gh-pages"
          git push origin gh-pages --force

      # Passo 4: Criar o arquivo .nojekyll
      - name: Enable GitHub Pages
        run: |
          echo "" > .nojekyll
          git add .nojekyll
          git commit -m "Habilitar o GitHub Pages"
          git push origin gh-pages

      # Passo 5: Publicar no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          folder: .
