name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write    # Permissão necessária para publicar no GitHub Pages
      id-token: write # Permissão necessária para autenticação
      contents: read  # Permissão necessária para acessar o conteúdo do repositório

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar o Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Passo 3: Upload dos arquivos para o Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      # Passo 4: Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
