name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Executa o workflow quando há alterações na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Substituir os placeholders pelos valores dos secrets
      - name: Replace Firebase Secrets in admin.html
        run: |
          sed -i "s|{{FIREBASE_API_KEY}}|${{ secrets.FIREBASE_API_KEY }}|g" admin.html
          sed -i "s|{{FIREBASE_APP_ID}}|${{ secrets.FIREBASE_APP_ID }}|g" admin.html
          sed -i "s|{{FIREBASE_AUTH_DOMAIN}}|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" admin.html
          sed -i "s|{{FIREBASE_DATABASE_URL}}|${{ secrets.FIREBASE_DATABASE_URL }}|g" admin.html
          sed -i "s|{{FIREBASE_MEASUREMENT_ID}}|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g" admin.html
          sed -i "s|{{FIREBASE_MESSAGING_SENDER_ID}}|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g" admin.html
          sed -i "s|{{FIREBASE_PROJECT_ID}}|${{ secrets.FIREBASE_PROJECT_ID }}|g" admin.html
          sed -i "s|{{FIREBASE_STORAGE_BUCKET}}|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" admin.html

      # Passo 3: Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          branch: gh-pages # Deploy será feito na branch 'gh-pages'
          folder: . # Deploy do conteúdo do repositório
